# -*- coding: CP1252 -*-
#
# generated by wxGlade 1.0.5 on Wed Oct 18 15:35:07 2023
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class ProcessUI(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ProcessUI.__init__
        kwds["style"] = kwds.get("style", 0)
        wx.Panel.__init__(self, *args, **kwds)

        sizer_2 = wx.BoxSizer(wx.VERTICAL)

        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(sizer_6, 0, wx.BOTTOM | wx.EXPAND | wx.TOP, 8)

        self.ButtonFilename = wx.Button(self, wx.ID_ANY, "Simulation Filename Browse ...", style=wx.BU_EXACTFIT)
        sizer_6.Add(self.ButtonFilename, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)

        self.LabelSimulationFilename = wx.StaticText(self, wx.ID_ANY, "none")
        sizer_6.Add(self.LabelSimulationFilename, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)

        self.panel_2 = wx.Panel(self, wx.ID_ANY)
        sizer_2.Add(self.panel_2, 0, wx.ALL, 8)

        sizer_3 = wx.StaticBoxSizer(wx.StaticBox(self.panel_2, wx.ID_ANY, "Time Course Settings"), wx.VERTICAL)

        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add(sizer_7, 1, wx.BOTTOM | wx.EXPAND | wx.TOP, 8)

        label_21 = wx.StaticText(self.panel_2, wx.ID_ANY, "# Time Points :")
        sizer_7.Add(label_21, 0, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT, 4)

        self.SpinTimePoints = wx.SpinCtrl(self.panel_2, wx.ID_ANY, "8", min=6, max=50, style=wx.ALIGN_CENTRE_HORIZONTAL)
        sizer_7.Add(self.SpinTimePoints, 0, 0, 0)

        label_22 = wx.StaticText(self.panel_2, wx.ID_ANY, "Start [sec] :")
        sizer_7.Add(label_22, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 8)

        self.TextTimeStart = wx.TextCtrl(self.panel_2, wx.ID_ANY, "0", style=wx.TE_CENTRE)
        sizer_7.Add(self.TextTimeStart, 0, wx.LEFT, 4)

        label_23 = wx.StaticText(self.panel_2, wx.ID_ANY, "Step [sec] :")
        sizer_7.Add(label_23, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 8)

        self.TextTimeStep = wx.TextCtrl(self.panel_2, wx.ID_ANY, "60", style=wx.TE_CENTRE)
        sizer_7.Add(self.TextTimeStep, 0, wx.LEFT, 4)

        self.panel_3 = wx.Panel(self, wx.ID_ANY)
        sizer_2.Add(self.panel_3, 0, wx.ALL | wx.EXPAND, 8)

        sizer_4 = wx.StaticBoxSizer(wx.StaticBox(self.panel_3, wx.ID_ANY, "Washin/Washout Waveform Settings"), wx.VERTICAL)

        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4.Add(sizer_8, 0, wx.ALL | wx.EXPAND, 8)

        label_24 = wx.StaticText(self.panel_3, wx.ID_ANY, "Repetitions (multiple of 1000) : ")
        sizer_8.Add(label_24, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.SpinRepetitions = wx.SpinCtrl(self.panel_3, wx.ID_ANY, "10", min=1, max=10, style=wx.ALIGN_CENTRE_HORIZONTAL)
        sizer_8.Add(self.SpinRepetitions, 0, 0, 0)

        sizer_8_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4.Add(sizer_8_copy, 0, wx.ALL | wx.EXPAND, 8)

        label_24_copy = wx.StaticText(self.panel_3, wx.ID_ANY, "Peak Amplitude (fixed value) : ")
        sizer_8_copy.Add(label_24_copy, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.SpinPeakAmplitude = wx.SpinCtrl(self.panel_3, wx.ID_ANY, "100", min=5, max=10000, style=wx.ALIGN_CENTRE_HORIZONTAL)
        sizer_8_copy.Add(self.SpinPeakAmplitude, 0, 0, 0)

        grid_sizer_1 = wx.FlexGridSizer(7, 7, 4, 4)
        sizer_4.Add(grid_sizer_1, 0, wx.ALL | wx.EXPAND, 6)

        label_1 = wx.StaticText(self.panel_3, wx.ID_ANY, "Parameter", style=wx.ALIGN_RIGHT)
        grid_sizer_1.Add(label_1, 0, wx.ALIGN_CENTER, 0)

        label_2 = wx.StaticText(self.panel_3, wx.ID_ANY, "Fixed \nValue", style=wx.ALIGN_CENTER_HORIZONTAL)
        grid_sizer_1.Add(label_2, 0, wx.ALIGN_CENTER, 0)

        label_3 = wx.StaticText(self.panel_3, wx.ID_ANY, "Apply", style=wx.ALIGN_CENTER_HORIZONTAL)
        grid_sizer_1.Add(label_3, 0, wx.ALIGN_CENTER, 0)

        label_4 = wx.StaticText(self.panel_3, wx.ID_ANY, "Steps", style=wx.ALIGN_CENTER_HORIZONTAL)
        grid_sizer_1.Add(label_4, 0, wx.ALIGN_CENTER, 0)

        label_5 = wx.StaticText(self.panel_3, wx.ID_ANY, "Start \nValue", style=wx.ALIGN_CENTER_HORIZONTAL)
        grid_sizer_1.Add(label_5, 0, wx.ALIGN_CENTER, 0)

        label_4_copy = wx.StaticText(self.panel_3, wx.ID_ANY, "Step Size", style=wx.ALIGN_CENTER_HORIZONTAL)
        grid_sizer_1.Add(label_4_copy, 0, wx.ALIGN_CENTER, 0)

        label_7 = wx.StaticText(self.panel_3, wx.ID_ANY, "Units/Comments", style=wx.ALIGN_CENTER_HORIZONTAL)
        grid_sizer_1.Add(label_7, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        label_8 = wx.StaticText(self.panel_3, wx.ID_ANY, "SNR [integer]", style=wx.ALIGN_RIGHT)
        grid_sizer_1.Add(label_8, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.TextFixedSnr = wx.TextCtrl(self.panel_3, wx.ID_ANY, "40", style=wx.TE_CENTRE)
        grid_sizer_1.Add(self.TextFixedSnr, 0, 0, 0)

        self.CheckSnr = wx.CheckBox(self.panel_3, wx.ID_ANY, "")
        grid_sizer_1.Add(self.CheckSnr, 0, wx.ALIGN_CENTER, 0)

        self.SpinStepsSnr = wx.SpinCtrl(self.panel_3, wx.ID_ANY, "1", min=1, max=100, style=wx.ALIGN_CENTRE_HORIZONTAL)
        grid_sizer_1.Add(self.SpinStepsSnr, 0, 0, 0)

        self.TextStartSnr = wx.TextCtrl(self.panel_3, wx.ID_ANY, "5", style=wx.TE_CENTRE)
        grid_sizer_1.Add(self.TextStartSnr, 0, 0, 0)

        self.TextStepSizeSnr = wx.TextCtrl(self.panel_3, wx.ID_ANY, "5", style=wx.TE_CENTRE)
        grid_sizer_1.Add(self.TextStepSizeSnr, 0, 0, 0)

        label_15_copy = wx.StaticText(self.panel_3, wx.ID_ANY, "PeakAmpl/RmsNoise", style=wx.ALIGN_LEFT)
        grid_sizer_1.Add(label_15_copy, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 4)

        label_9 = wx.StaticText(self.panel_3, wx.ID_ANY, "Delay 1 [sec]")
        grid_sizer_1.Add(label_9, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.TextFixedDelay1 = wx.TextCtrl(self.panel_3, wx.ID_ANY, "-40", style=wx.TE_CENTRE)
        grid_sizer_1.Add(self.TextFixedDelay1, 0, 0, 0)

        self.CheckDelay1 = wx.CheckBox(self.panel_3, wx.ID_ANY, "")
        grid_sizer_1.Add(self.CheckDelay1, 0, wx.ALIGN_CENTER, 0)

        self.SpinStepsDelay1 = wx.SpinCtrl(self.panel_3, wx.ID_ANY, "1", min=1, max=100, style=wx.ALIGN_CENTRE_HORIZONTAL)
        grid_sizer_1.Add(self.SpinStepsDelay1, 0, 0, 0)

        self.TextStartDelay1 = wx.TextCtrl(self.panel_3, wx.ID_ANY, "-50", style=wx.TE_CENTRE)
        grid_sizer_1.Add(self.TextStartDelay1, 0, 0, 0)

        self.TextStepSizeDelay1 = wx.TextCtrl(self.panel_3, wx.ID_ANY, "10", style=wx.TE_CENTRE)
        grid_sizer_1.Add(self.TextStepSizeDelay1, 0, 0, 0)

        label_15 = wx.StaticText(self.panel_3, wx.ID_ANY, "n/a", style=wx.ALIGN_LEFT)
        grid_sizer_1.Add(label_15, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 4)

        label_10 = wx.StaticText(self.panel_3, wx.ID_ANY, "Delay 2 [sec]")
        grid_sizer_1.Add(label_10, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.TextFixedDelay2 = wx.TextCtrl(self.panel_3, wx.ID_ANY, "200", style=wx.TE_CENTRE)
        grid_sizer_1.Add(self.TextFixedDelay2, 0, 0, 0)

        self.CheckDelay2 = wx.CheckBox(self.panel_3, wx.ID_ANY, "")
        grid_sizer_1.Add(self.CheckDelay2, 0, wx.ALIGN_CENTER, 0)

        self.SpinStepsDelay2 = wx.SpinCtrl(self.panel_3, wx.ID_ANY, "1", min=1, max=100, style=wx.ALIGN_CENTRE_HORIZONTAL)
        grid_sizer_1.Add(self.SpinStepsDelay2, 0, 0, 0)

        self.TextStartDelay2 = wx.TextCtrl(self.panel_3, wx.ID_ANY, "100", style=wx.TE_CENTRE)
        grid_sizer_1.Add(self.TextStartDelay2, 0, 0, 0)

        self.TextStepSizeDelay2 = wx.TextCtrl(self.panel_3, wx.ID_ANY, "50", style=wx.TE_CENTRE)
        grid_sizer_1.Add(self.TextStepSizeDelay2, 0, 0, 0)

        label_16 = wx.StaticText(self.panel_3, wx.ID_ANY, "n/a", style=wx.ALIGN_LEFT)
        grid_sizer_1.Add(label_16, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 4)

        label_11 = wx.StaticText(self.panel_3, wx.ID_ANY, "Rate 1 [sec]", style=wx.ALIGN_RIGHT)
        grid_sizer_1.Add(label_11, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.TextFixedRate1 = wx.TextCtrl(self.panel_3, wx.ID_ANY, "25", style=wx.TE_CENTRE)
        grid_sizer_1.Add(self.TextFixedRate1, 0, 0, 0)

        self.CheckRate1 = wx.CheckBox(self.panel_3, wx.ID_ANY, "")
        grid_sizer_1.Add(self.CheckRate1, 0, wx.ALIGN_CENTER, 0)

        self.SpinStepsRate1 = wx.SpinCtrl(self.panel_3, wx.ID_ANY, "1", min=1, max=100, style=wx.ALIGN_CENTRE_HORIZONTAL)
        grid_sizer_1.Add(self.SpinStepsRate1, 0, 0, 0)

        self.TextStartRate1 = wx.TextCtrl(self.panel_3, wx.ID_ANY, "10", style=wx.TE_CENTRE)
        grid_sizer_1.Add(self.TextStartRate1, 0, 0, 0)

        self.TextStepSizeRate1 = wx.TextCtrl(self.panel_3, wx.ID_ANY, "5", style=wx.TE_CENTRE)
        grid_sizer_1.Add(self.TextStepSizeRate1, 0, 0, 0)

        label_18_copy = wx.StaticText(self.panel_3, wx.ID_ANY, "rate for wash in", style=wx.ALIGN_LEFT)
        grid_sizer_1.Add(label_18_copy, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 4)

        label_11_copy = wx.StaticText(self.panel_3, wx.ID_ANY, "Rate 2 [sec]", style=wx.ALIGN_RIGHT)
        grid_sizer_1.Add(label_11_copy, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.TextFixedRate2 = wx.TextCtrl(self.panel_3, wx.ID_ANY, "25", style=wx.TE_CENTRE)
        grid_sizer_1.Add(self.TextFixedRate2, 0, 0, 0)

        self.CheckRate2 = wx.CheckBox(self.panel_3, wx.ID_ANY, "")
        grid_sizer_1.Add(self.CheckRate2, 0, wx.ALIGN_CENTER, 0)

        self.SpinStepsRate2 = wx.SpinCtrl(self.panel_3, wx.ID_ANY, "1", min=1, max=100, style=wx.ALIGN_CENTRE_HORIZONTAL)
        grid_sizer_1.Add(self.SpinStepsRate2, 0, 0, 0)

        self.TextStartRate2 = wx.TextCtrl(self.panel_3, wx.ID_ANY, "10", style=wx.TE_CENTRE)
        grid_sizer_1.Add(self.TextStartRate2, 0, 0, 0)

        self.TextStepSizeRate2 = wx.TextCtrl(self.panel_3, wx.ID_ANY, "5", style=wx.TE_CENTRE)
        grid_sizer_1.Add(self.TextStepSizeRate2, 0, 0, 0)

        label_18 = wx.StaticText(self.panel_3, wx.ID_ANY, "rate for wash out", style=wx.ALIGN_LEFT)
        grid_sizer_1.Add(label_18, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 4)

        label_13 = wx.StaticText(self.panel_3, wx.ID_ANY, "Base [% Noise]", style=wx.ALIGN_RIGHT)
        grid_sizer_1.Add(label_13, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.TextFixedBase = wx.TextCtrl(self.panel_3, wx.ID_ANY, "10", style=wx.TE_CENTRE)
        grid_sizer_1.Add(self.TextFixedBase, 0, 0, 0)

        self.CheckBase = wx.CheckBox(self.panel_3, wx.ID_ANY, "")
        grid_sizer_1.Add(self.CheckBase, 0, wx.ALIGN_CENTER, 0)

        self.SpinStepsBase = wx.SpinCtrl(self.panel_3, wx.ID_ANY, "1", min=1, max=10, style=wx.ALIGN_CENTRE_HORIZONTAL)
        grid_sizer_1.Add(self.SpinStepsBase, 0, 0, 0)

        self.TextStartBase = wx.TextCtrl(self.panel_3, wx.ID_ANY, "0", style=wx.TE_CENTRE)
        grid_sizer_1.Add(self.TextStartBase, 0, 0, 0)

        self.TextStepSizeBase = wx.TextCtrl(self.panel_3, wx.ID_ANY, "", style=wx.TE_CENTRE)
        grid_sizer_1.Add(self.TextStepSizeBase, 0, 0, 0)

        label_19 = wx.StaticText(self.panel_3, wx.ID_ANY, "n/a", style=wx.ALIGN_LEFT)
        grid_sizer_1.Add(label_19, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 4)

        sizer_9 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Comment - Please annotate what you are doing in this simulation!"), wx.VERTICAL)
        sizer_2.Add(sizer_9, 1, wx.ALL | wx.EXPAND, 8)

        self.TextComment = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_MULTILINE | wx.TE_WORDWRAP)
        sizer_9.Add(self.TextComment, 1, wx.EXPAND, 0)

        self.panel_4 = wx.Panel(self, wx.ID_ANY)
        sizer_2.Add(self.panel_4, 0, wx.ALL | wx.EXPAND, 8)

        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)

        self.ButtonCreate = wx.Button(self.panel_4, wx.ID_ANY, "Create Simulated Data")
        sizer_5.Add(self.ButtonCreate, 1, wx.EXPAND, 0)

        self.ButtonDefaults = wx.Button(self.panel_4, wx.ID_ANY, "Reset to Defaults")
        sizer_5.Add(self.ButtonDefaults, 1, 0, 0)

        self.ButtonCancel = wx.Button(self.panel_4, wx.ID_ANY, "Cancel")
        self.ButtonCancel.Hide()
        sizer_5.Add(self.ButtonCancel, 1, wx.EXPAND, 0)

        self.panel_4.SetSizer(sizer_5)

        self.panel_3.SetSizer(sizer_4)

        self.panel_2.SetSizer(sizer_3)

        self.SetSizer(sizer_2)

        self.Layout()

        self.Bind(wx.EVT_BUTTON, self.on_simulation_filename, self.ButtonFilename)
        self.Bind(wx.EVT_CHECKBOX, self.on_steps_rate_out, self.CheckRate2)
        self.Bind(wx.EVT_BUTTON, self.on_create, self.ButtonCreate)
        self.Bind(wx.EVT_BUTTON, self.on_reset, self.ButtonDefaults)
        self.Bind(wx.EVT_BUTTON, self.on_cancel, self.ButtonCancel)
        # end wxGlade

    def on_simulation_filename(self, event):  # wxGlade: ProcessUI.<event_handler>
        print("Event handler 'on_simulation_filename' not implemented!")
        event.Skip()

    def on_steps_rate_out(self, event):  # wxGlade: ProcessUI.<event_handler>
        print("Event handler 'on_steps_rate_out' not implemented!")
        event.Skip()

    def on_create(self, event):  # wxGlade: ProcessUI.<event_handler>
        print("Event handler 'on_create' not implemented!")
        event.Skip()

    def on_reset(self, event):  # wxGlade: ProcessUI.<event_handler>
        print("Event handler 'on_reset' not implemented!")
        event.Skip()

    def on_cancel(self, event):  # wxGlade: ProcessUI.<event_handler>
        print("Event handler 'on_cancel' not implemented!")
        event.Skip()

# end of class ProcessUI

class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0)
        wx.Frame.__init__(self, *args, **kwds)
        self.SetTitle("frame_1")

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        self.ProcessUI = ProcessUI(self, wx.ID_ANY)
        sizer_1.Add(self.ProcessUI, 1, wx.EXPAND, 0)

        self.SetSizer(sizer_1)
        sizer_1.Fit(self)

        self.Layout()
        # end wxGlade

# end of class MyFrame
